config/routes.rb
DsoWeb::Application.routes.draw do
  
  resources :prospies


  resources :orchestra_sections


  resources :contacts


  resources :pages

  resources :abouts
  resources :about, :controller => "abouts"

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :concerts


  resources :staffs
  resources :staff, :controller => "staffs"
  resources :members, :controller => "orchestra_sections"

  resources :news, :controller => "events"

  resources :auditions


  root to: 'pages#index'
  resources :events

end

app/models/about.rb
class About
  include Mongoid::Document
  field :image
  field :description
end

app/models/admin_user.rb
class AdminUser
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/models/audition.rb
class Audition
  include Mongoid::Document
  field :date, :type => Date
  field :times
  field :location
  field :description
  validates_presence_of :date
  validates_presence_of :times
  validates_presence_of :location
  validates_presence_of :description
end

app/models/concert.rb
class Concert
  include Mongoid::Document
  field :name
  field :date, :type => Date
  field :time
  field :description
  field :image, default: -> { "http://" }
  field :ticket, default: -> { "http://" }
  field :buttonText, default: -> { "Get Tickets" }
  field :blackText

  validates_presence_of :name
  validates_presence_of :date
  validates_presence_of :time
  validates_presence_of :description
  validates_presence_of :ticket
end

app/models/contact.rb
class Contact
  include Mongoid::Document
  field :category
  field :manager_1
  field :manager_2
end

app/models/event.rb
class Event
  include Mongoid::Document
  field :name
  field :tag
  field :description
  field :date, :type => Date, default: -> { Date.today.to_s }
  validates_presence_of :name
  validates_presence_of :date
end

app/models/member.rb
class Member
  include Mongoid::Document
  field :name
  embedded_in :OrchestraSection
end

app/models/orchestra_section.rb
class OrchestraSection
  include Mongoid::Document
  field :name
  field :position
  embeds_many :members
  accepts_nested_attributes_for :members, :allow_destroy => true
end

app/models/page.rb
class Page
  include Mongoid::Document
  field :title
end

app/models/pages.rb
class Pages
  include Mongoid::Document
  field :title
end

app/models/prospy.rb
class Prospy
  include Mongoid::Document
  field :image
  field :description
end

app/models/staff.rb
class Staff
  include Mongoid::Document
  field :team, type: String
  field :name, type: String
  field :position, type: String
  field :photo, type: String
  field :email, type: String
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@concert = Concert.where(:date.gte => Date.today.to_s).order_by(:date => :asc).first
  	unless @concert
  		@concert = Concert.order_by(:date => :desc).first
  	end
  	@events = Event.order_by(:date => :desc).limit(3)
  end
end

app/controllers/staffs_controller.rb
class StaffsController < InheritedResources::Base
  def index
    @creatives = Staff.where(team: 'creative').all
    @management = Staff.all.where(team: 'management').all
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Returns the name of the application.
  def app_name
    "DSO"
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    if page_title.empty?
      app_name
    else
      "#{page_title} | #{app_name}"
    end
  end

  # Returns current if path the current path
  def cp(path)
    "current" if current_page?(path)
  end

  def about_path
    '/about'
  end

  def staff_path
    '/staff'
  end

  def news_path
    '/news'
  end

  def members_path
    '/members'
  end
end

app/helpers/auditions_helper.rb
module AuditionsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prospies_helper.rb
module ProspiesHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.slim
= form_for @staff do |f|
  - if @staff.errors.any?
    #error_explanation
      h2 = "#{pluralize(@staff.errors.count, "error")} prohibited this staff from being saved:"
      ul
        - @staff.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :team
    = f.text_field :team
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :position
    = f.text_field :position
  .field
    = f.label :photo
    = f.text_field :photo
  .actions = f.submit 'Save'

app/views/staffs/edit.html.slim
h1 Editing staff

== render 'form'

= link_to 'Show', @staff
'|
= link_to 'Back', staffs_path

app/views/staffs/index.html.slim
- provide(:title, 'Staff | Dartmouth Symphony Orchestra')
#main
  .container.staff.mainEvent
    / .row
    /   .twelvecol.last.center
    /     h1
    /       | DSO Staff
    /     p
    /       | At the DSO, we pride ourselves in the professionalism of our creative staff, as well as our student managers.
  .container.news.section
    .row
      .twelvecol.last.center
        h3
          = "Creative Team"
  .container.staff.center.section
    .row
      - for staff in @creatives do
        - if cycle('1', '2') == ('1')
          | <div class="row">
          .twocol
          .fourcol
            .portrait[style='#{ staff.photo.present? ? "background-image:url(#{staff.photo})" : "" }']
            .h3 = staff.name
            small.position = staff.position 
        - else
          .fourcol.last
            .portrait[style='#{ staff.photo.present? ? "background-image:url(#{staff.photo})" : "" }']
            .h3 = staff.name
            small.position = staff.position
          | </div>
  .container.news.section
    .row
      .twelvecol.last.center
        h3
          = "Management Team"
  .container.staff.center.section
    - for staff in @management do
      - if cycle('1', '2') == ('1')
        | <div class="row">
        .twocol
        .fourcol
          .portrait[style='#{ staff.photo.present? ? "background-image:url(#{staff.photo})" : "" }']
          .h3 = staff.name
          small.position = staff.position 
      - else
        .fourcol.last
          .portrait[style='#{ staff.photo.present? ? "background-image:url(#{staff.photo})" : "" }']
          .h3 = staff.name
          small.position = staff.position
        | </div>

app/views/staffs/new.html.slim
h1 New staff

== render 'form'

= link_to 'Back', staffs_path

app/views/staffs/show.html.slim
p#notice = notice

p
  strong Team:
  = @staff.team
p
  strong Name:
  = @staff.name
p
  strong Position:
  = @staff.position
p
  strong Photo:
  = @staff.photo

= link_to 'Edit', edit_staff_path(@staff)
'|
= link_to 'Back', staffs_path