config/routes.rb
DsoWeb::Application.routes.draw do
  
  resources :prospies


  resources :orchestra_sections


  resources :contacts


  resources :pages

  resources :abouts
  resources :about, :controller => "abouts"

  ActiveAdmin.routes(self)
  devise_for :admin_users, ActiveAdmin::Devise.config

  resources :concerts


  resources :staffs
  resources :staff, :controller => "staffs"
  resources :members, :controller => "orchestra_sections"

  resources :news, :controller => "events"

  resources :auditions


  root to: 'pages#index'
  resources :events

end

app/models/about.rb
class About
  include Mongoid::Document
  field :image
  field :description
end

app/models/admin_user.rb
class AdminUser
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""
  
  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  # field :confirmation_token,   :type => String
  # field :confirmed_at,         :type => Time
  # field :confirmation_sent_at, :type => Time
  # field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String
end

app/models/audition.rb
class Audition
  include Mongoid::Document
  field :date, :type => Date
  field :times
  field :location
  field :description
  validates_presence_of :date
  validates_presence_of :times
  validates_presence_of :location
  validates_presence_of :description
end

app/models/concert.rb
class Concert
  include Mongoid::Document
  field :name
  field :date, :type => Date
  field :time
  field :description
  field :image, default: -> { "http://" }
  field :ticket, default: -> { "http://" }
  field :buttonText, default: -> { "Get Tickets" }
  field :blackText

  validates_presence_of :name
  validates_presence_of :date
  validates_presence_of :time
  validates_presence_of :description
  validates_presence_of :ticket
end

app/models/contact.rb
class Contact
  include Mongoid::Document
  field :category
  field :manager_1
  field :manager_2
end

app/models/event.rb
class Event
  include Mongoid::Document
  field :name
  field :tag
  field :description
  field :date, :type => Date, default: -> { Date.today.to_s }
  validates_presence_of :name
  validates_presence_of :date
end

app/models/member.rb
class Member
  include Mongoid::Document
  field :name
  embedded_in :OrchestraSection
end

app/models/orchestra_section.rb
class OrchestraSection
  include Mongoid::Document
  field :name
  field :position
  embeds_many :members
  accepts_nested_attributes_for :members, :allow_destroy => true
end

app/models/page.rb
class Page
  include Mongoid::Document
  field :title
end

app/models/pages.rb
class Pages
  include Mongoid::Document
  field :title
end

app/models/prospy.rb
class Prospy
  include Mongoid::Document
  field :image
  field :description
end

app/models/staff.rb
class Staff
  include Mongoid::Document
  field :team, type: String
  field :name, type: String
  field :position, type: String
  field :photo, type: String
  field :email, type: String
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/auditions_helper.rb
module AuditionsHelper
end

app/helpers/concerts_helper.rb
module ConcertsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/prospies_helper.rb
module ProspiesHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/layouts/_nav.html.slim
ul.nav
  li #{link_to '', root_path, :class => 'root_link', :target => "_top"}
  li #{link_to 'About', 'about', :class => "home #{cp(about_path)}", :target => "_top"}
  li #{link_to 'News', 'news', :class => "home #{cp(news_path)}", :target => "_top"}
  li #{link_to 'Staff', 'staff', :class => "home #{cp(staff_path)}", :target => "_top"}
  li #{link_to 'Members', 'members', :class => "home #{cp(members_path)}", :target => "_top"}
  li #{link_to 'Auditions', auditions_path, :class => "home #{cp(auditions_path)}", :target => "_top"}
  li #{link_to 'Contact', contacts_path, :class => "home #{cp(contacts_path)}", :target => "_top"}

app/views/layouts/application.html.slim
doctype html
html
  head
    title= full_title(yield(:title))
    meta content="text/html; charset=utf-8" http-equiv="Content-Type"
    meta content="Dartmouth Symphony Orchestra, DSO" name="author"
    meta content="document" name="resource-type"
    meta content="global" name="distribution"
    meta content="general" name="rating"
    meta content="ALL" name="robots"
    meta content="Copyright 2011 Dartmouth Symphony Orchestra." name="copyright"
    meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
    meta content="The Dartmouth Symphony Orchestra, or DSO is the resident symphony orchestra at Dartmouth College." name="description"
    meta content="dartmouth symphony orchestra, dso, anthony princiotti, princiotti, dartmouth, college, university, orchestra, symphony, ivy league, new hampshire, new england, music, mangosango" name="keywords"
    = javascript_include_tag "application"
    = stylesheet_link_tag    "application", media: "all"
    link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700' rel='stylesheet' type='text/css'
    link href='http://fonts.googleapis.com/css?family=Open+Sans:300,400' rel='stylesheet' type='text/css'
    link href='http://fonts.googleapis.com/css?family=Roboto+Slab:700,400,300' rel='stylesheet' type='text/css'
  body
    #openBar
      = link_to raw(' <i class="icon-list"></i>'), '#', :id => 'openMenu'
    #leftBar
      = render 'layouts/nav'
    #wrapper
      = yield
  .container.footer

app/views/pages/about.index.slim
- provide(:title, 'About | Dartmouth Symphony Orchestra')
#main
  .container.mainEvent[style='#{ @about.image.present? ? "background-image:url(#{@about.image})" : "" }']
    .row
      .twelvecol.last
        raw(#{@about.description})

app/views/pages/index.html.slim
- provide(:title, 'Dartmouth Symphony Orchestra')
#main
  .container.mainEvent[style='#{ @concert.image.present? ? "background-image:url(#{@concert.image})" : "" }']
    .row
      .twelvecol.last[style='#{ @concert.blackText.present? ? "color:#333" : "" }']
        small = @concert.date
        h1 = @concert.name
        p = @concert.description
        a.button[href="#{ @concert.ticket ? @concert.ticket : '#' }" target="top"]
          = @concert.buttonText

  .container.news.section
    .row
      .twelvecol.last.center
        h3.animate.fadeIn
          i[class='icon-newspaper']
          = "News"
  .container.news
    - for event in @events do
      .row
        .twocol
        .eightcol.last
          article
            h4.articleTitle = event.name
            small.articleDate = event.date
            hr
            p = raw(event.description)
      .dotted-border
  .container.news
    .row
      .twelvecol.paginate
        .center = link_to 'View More News', 'news', :target => '_top'

- unless @concert.image.present?
  video id="video_background" preload="auto" muted="true" loop="loop" canplay="false" class="is-vertical" autoplay="true"
    /source src="https://cloud.box.com/shared/static/dw0qwu2duzh476cpugzh.webm" type="video/webm"
    source src="https://cloud.box.com/shared/static/s8tln5lodvce7hpebsz8.mp4" type="video/mp4"